### ISSUE TITLE
UnableToResolveError

### ISSUE THREAD

**Issue by achmadk** [qiscus/react-native-qiscus-sdk-js#1]
I try to use this module same as in [README](https://github.com/qiscus/react-native-qiscus-sdk-js) . After execute `react-native run-android`, I got error message 
```bash
bundling failed: UnableToResolveError: Unable to resolve module `react-native/Libraries/Renderer/src/renderers/native/ReactNativePropRegistry` from `${MY_PROJECT_DIRECTORY}\node_modules\react-native-qiscus-sdk\node_modules\native-base\dist\src\Utils\computeProps.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
```
I use `react 16.0.0-beta.5`, `react-native 0.49.5`, and `native-base 2.3.3` (latest version).

I have done delete `node_modules` folder and execute `npm start -- --reset-cache`, but that error still displayed.

**Comment by theredfoxfire** [comment]
Beware please since this SDK use native-base component which require
"react-native":
"0.45.1" higher react-native version not supported yet, lower version are
welcome.

You can specified react-native version in your new project by run this
command react-native init AppSDK --version 0.45.1

I am figured you are using react native 0.49 and not supported on this
version, I will remove native base dependency on the next release, but for
now downgrade your react native version into 0.45.1 will solve the problem.

I try to use this module same as in README
<https://github.com/qiscus/react-native-qiscus-sdk-js> . After execute
react-native
run-android, I got error message

bundling failed: UnableToResolveError: Unable to resolve module
`react-native/Libraries/Renderer/src/renderers/native/ReactNativePropRegistry`
from `${MY_PROJECT_DIRECTORY}\node_modules\react-native-qiscus-sdk\node_modules\native-base\dist\src\Utils\computeProps.js`:
Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --
--reset-cache`.

I use react 16.0.0-beta.5, react-native 0.49.5, and native-base 2.3.3
(latest version).

I have done delete node_modules folder and execute npm start --
--reset-cache, but that error still displayed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/qiscus/react-native-qiscus-sdk-js/issues/1>, or mute
the thread
