### ISSUE TITLE
add loading indicator when submitting new text or new picture

### ISSUE THREAD

**Issue by achmadk** [qiscus/react-native-qiscus-sdk-js#4]
when submitting new text or new picture, it has not displaying loading indicator so that the user thinks that the text or picture is not sent successfully.

**Comment by theredfoxfire** [comment]
Sure we are still working on this SDK. Wait for the next release, thank you for using RN Qiscus SDK.

**Comment by theredfoxfire** [comment]
hey @achmadk I've release 0.1.2 could you please update your react-native-qiscus-sdk into 0.1.2. Hopefully will solve this issue. For now I will close this, feel free to reopen when you find this issue coming up.

**Comment by achmadk** [comment]
Hi, @theredfoxfire . I have updated react-native-qiscus-sdk to 0.1.2. Unfortunately, it doesn't resolve this issue. Maybe `this.setState` function inside `keyboardWillHide` event handler causing my app is slowed down, so loading indicator is not shown.

**Comment by theredfoxfire** [comment]
`keyboardWillHide` this method just do update state style and it's not part of loading indicator. about slowing down I am not sure, if update state style will effect your simulator performance. can you please give a try on real device? because simulator it's complicated thing. simulator's tightly depend on your environment
